#:schema node_modules/wrangler/config-schema.json
name = "pengxutao-home"
compatibility_date = "2026-6-01"
compatibility_flags = [ "nodejs_compat" ]

# 告诉 Cloudflare Pages 静态资源的输出目录
pages_build_output_dir = ".open-next/cloudflare"